### PR TITLE
fix(#318): the variable containing map of strategy configs is dumped as well

### LINKED ISSUE #318: Categorized strategy properties are not being recognized when using a configuration file
##### Issue Overview

Properties from configuration file are not getting mapped into the `categorized` strategy configuration.

##### Expected Behaviour

When running smart testing with the `categorized` strategy and a configuration file, smart testing should configure the `categorized` strategy from configuration file correctly. 

##### Current Behaviour

When running smart testing with `categorized` strategy and a configuration file, properties set in that file are not being recognized by the execution itself. According to the `report.xml` smart testing sees only, that the categorized strategy has been applied, but all the properties are ignored.
```xml
 <executionConfiguration>
        <usageMode>selecting</usageMode>
        <strategies>
            <strategy>categorized</strategy>
        </strategies>
        <properties>
            <property name="smart.testing" value="categorized"/>
        </properties>
    </executionConfiguration
```
Running smart testing with properties set as command line arguments are recognized properly.

##### Steps To Reproduce
1. Clone this repository https://github.com/spriadka/testsuite/tree/7.1.x-categories
2. Set up the machine according to the README
3. Create `smart-testing.yml` following:
``` yaml
strategies: categorized
debug: true
strategiesConfiguration:
  categorized:
    categories: Elytron
```
4. Execute following command 
```bash
mvn -Pbasic,standalone -Djboss.dist=<your_jboss_dist> -Darq.extension.webdriver.firefox_binary=<your_ff_binary_path> -Dtest="ElytronPolicyTestCase*" test
```
5. See the `basic/target/.smart-testing/report.xml`

### PR DESCRIPTION
**Pull request by MatousJobanek**
#### Short description of what this resolves:

The variable containing a map of raw strategy configs is dumped into the precalculated config as well to make it available for later loading directly from the strategy implementations.

#### Changes proposed in this pull request:

- Renamed `strategiesConfig` to `rawStrategyConfigurations`
- created getter to add the `rawStrategyConfigurations` variable to the dumped file
- fixed test-bed implementation to allow adding strategy configurations
- changed the logic that loads strategy configurations from the file - added a detection when the strategy config is not a map, but a list - eg. in this case:
```yaml
{autocorrect: false, customProviders: [], customStrategies: [], debug: false, disable: false,
  strategies: [categorized], strategiesConfiguration: [categorized: {
      caseSensitive: false, categories: [LoaderCategory, serviceCategory], matchAll: false,
      methods: false, reversed: false}]}
```

Fixes #318

### CODE REVIEW

File: core/src/main/java/org/arquillian/smart/testing/configuration/ConfigurationLoader.java [hunk 1]
```diff
@@ -108,7 +109,16 @@ private static Configuration loadAsConfiguration(Map<String, Object> yamlConfigu
 
         final Configuration configuration = mapToObject(Configuration.class, yamlConfiguration);
         if (strategiesConfiguration != null) {
-            configuration.setStrategiesConfig((Map<String, Object>) strategiesConfiguration);
+            if (strategiesConfiguration instanceof Map) {
+                configuration.setRawStrategyConfigurations((Map<String, Object>) strategiesConfiguration);
+
+            } else if (strategiesConfiguration instanceof List) {
+                HashMap<String, Object> configMap = new HashMap<>();
```
Comment (lordofthejars) [inline core/src/main/java/org/arquillian/smart/testing/configuration/ConfigurationLoader.java]: `Map<String, String> configMap`

Comment (MatousJobanek) [reply core/src/main/java/org/arquillian/smart/testing/configuration/ConfigurationLoader.java]: no, it's `HashMap<String, Object>` see the parameter in `Configuration` class

Comment (lordofthejars) [reply core/src/main/java/org/arquillian/smart/testing/configuration/ConfigurationLoader.java]: Sorry I meant `Map<String, Object>`using the interface not the implementation.

Comment (MatousJobanek) [reply core/src/main/java/org/arquillian/smart/testing/configuration/ConfigurationLoader.java]: Ok, yeah, sure :-)
