### PR TITLE
Suggests closest matching strategy when mistyped

### LINKED ISSUE #170: Suggest closest matching strategy when mispelled
##### Issue Overview

Currently, we fail when we can't find a strategy. See #167 for details.

##### Expected Behaviour

Based on https://en.wikipedia.org/wiki/Levenshtein_distance we can suggest matching strategy.

 `Did you mean changed instead of cahnged?`.

##### Current Behaviour

Failing with an error.

##### Steps To Reproduce
1. misspell strategy when configuring the build
2. run the build

### PR DESCRIPTION
**Pull request by bartoszmajsak**
#### Short description of what this resolves:

With #171 we introduced an exception informing about not existing strategy. This PR brings a suggestion which one could have been the intended one by still failing the build early, but hinting the user with

```
[ERROR] [Smart Testing Extension] Unable to find strategy [chaenged]. Did you mean [changed]?                                                                                                                                                                                              
[ERROR] [Smart Testing Extension] Unable to find strategy [neew]. Did you mean [new]?                                                                                                                                                                                                      
[ERROR] Internal error: java.lang.IllegalStateException: Unknown strategies (see above). Please refer to http://arquillian.org/smart-testing/#
_strategies for the list of available strategies. -> [Help 1]                                                                                 
org.apache.maven.InternalErrorException: Internal error: java.lang.IllegalStateException: Unknown strategies (see above). Please refer to http
://arquillian.org/smart-testing/#_strategies for the list of available strategies.                                                            
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:122)                                                                       
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)    
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)     
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)       
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                      
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                              
        at java.lang.reflect.Method.invoke(Method.java:498)            
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)                                                
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)                                                        
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)                                              
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)            
```

Fixes #170

### CODE REVIEW

File: functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/MisspelledStrategiesFunctionalTest.java [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+import org.junit.Test;
+
+import static org.arquillian.smart.testing.Configuration.SMART_TESTING_DEBUG;
+import static org.arquillian.smart.testing.ftest.testbed.TestRepository.testRepository;
+import static org.arquillian.smart.testing.ftest.testbed.configuration.Mode.ORDERING;
+import static org.arquillian.smart.testing.scm.ScmRunnerProperties.COMMIT;
+import static org.arquillian.smart.testing.scm.ScmRunnerProperties.PREVIOUS_COMMIT;
+import static org.assertj.core.api.Assertions.assertThat;
+
+public class MisspelledStrategiesFunctionalTest {
```
Comment (lordofthejars) [inline functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/MisspelledStrategiesFunctionalTest.java]: Do we need a functional test for this feature? I am thinking in terms of pipeline performance but also in terms of that maybe unit tests here is enough

Comment (bartoszmajsak) [reply functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/MisspelledStrategiesFunctionalTest.java]: Depends how we want to evolve this feature. If we want to have autocorrect then this would be good to have. Also the build here takes few seconds really.

Comment (lordofthejars) [reply functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/MisspelledStrategiesFunctionalTest.java]: ok

**Comment by dipak-pawar** [comment]
@bartoszmajsak How about using that strategy instead of suggesting?

**Comment by bartoszmajsak** [comment]
@dipak-pawar that would be another feature - to enable autocorrect. I will open an issue for it.

**Comment by bartoszmajsak** [comment]
Follow-up about autocorrect #173 - needs discussion.
