### PR TITLE
fix(ext) Excluding jar signatures from shaded jar

### LINKED ISSUE #175: Shaded extension doesn't work with older versions of Maven
##### Issue Overview

Following the guide, I copied shaded extension (`maven-lifecycle-extension-0.0.1-shaded.jar`) into `M2_HOME/lib/ext`, but when running the build nothing happens (no sign of extension in the logs).

##### Expected Behaviour

The extension is working after installing it by [following the guide](http://arquillian.org/smart-testing/#_maven_3_1_x).

##### Current Behaviour

No signs of extension kicking in (nothing in the logs).

##### Steps To Reproduce

1. Change Maven to version pre `3.3.x`
2. Download extension from [Maven Central](http://central.maven.org/maven2/org/arquillian/smart/testing/maven-lifecycle-extension/0.0.1/maven-lifecycle-extension-0.0.1-shaded.jar)
3. Copy to `M2_HOME/lib/ext`
4. Run the build using e.g. `mvn clean package -Dsmart.testing=new,changed -Dsmart.testing.mode=selecting`

##### Additional Information

```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: /usr/share/maven/apache-maven-3.2.5
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_144/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.12.9-300.fc26.x86_64", arch: "amd64", family: "unix"
arquillian-core [mvn --version]
```

### PR DESCRIPTION
**Pull request by MatousJobanek**
#### Short description of what this resolves:

Excluding jar signatures:
```
META-INF/*.SF
META-INF/*.DSA
META-INF/*.RSA
```
from the shaded jar that is used for maven extension in older Maven versions. 
If they are present, the shaded jar is not properly loaded and Maven extension doesn't work

Fixes #175

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Great find Matous! Thank you so much. Just one thought - would it make sense to have smoke test for that to make sure that we have this support always working?

**Comment by lordofthejars** [comment]
I think it does not pay off of for now. If we have any regression then I'll create the test, but for now we are not sure if people is using it or not.

**Comment by MatousJobanek** [comment]
I'll create a test for it, I think that it is essential - I have an idea how to do it. I just didn't have time yesterday ;-)

**Comment by bartoszmajsak** [comment]
> I think it does not pay off of for now. If we have any regression then I'll create the test, but for now we are not sure if people is using it or not.

I think we should try to be reasonably pragmatic here. What you are proposing is equal to removing this feature entirely. How can I know that it works now? I would need to do the manual verification. And for each and every release I would still need to do that, otherwise, we would ship something totally broken. This is exactly what we had till now, just believing that stuff works. So having a test which captures that regression is essential. Thanks @MatousJobanek for your effort on making this happen!

File: functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/BuildConfigurator.java [hunk 1]
```diff
@@ -38,6 +38,7 @@
     private boolean skipTests = false;
     private File workingDirectory;
     private String mavenOpts = "-Xms512m -Xmx1024m";
+    private String maven3Version;
```
Comment (bartoszmajsak) [inline functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/BuildConfigurator.java]: Minor detail - I'm not sure if `3` brings any extra clarity here.

File: functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionRegisterer.java [hunk 2]
```diff
@@ -1,16 +1,22 @@
...
+import java.nio.file.Paths;
+import java.util.Arrays;
+import java.util.Optional;
 import java.util.stream.Collectors;
+import org.jboss.shrinkwrap.resolver.api.maven.Maven;
 
 class MavenExtensionRegisterer {
 
-    private static final String EXTENSIONS_XML = "extensions.xml";
+    public static final String DOT_MVN_DIR = ".mvn";
```
Comment (bartoszmajsak) [inline functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionRegisterer.java]: How about `MVN_CONFIG_DIR`?

File: functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionRegisterer.java [hunk 3]
```diff
@@ -36,4 +42,37 @@ void addSmartTestingExtension(String version) {
...
+                .findFirst();
+            if (!mvnHome.isPresent()) {
+                throw new IllegalStateException(String.format(
+                    "There is no %s directory present inside of the %s directory. The extension cannot be installed.",
+                    mvnHomeName, resolverMaven));
+            }
+            Path libExtDir = mvnHome.get().resolve("lib").resolve("ext");
+            if (!libExtDir.toFile().exists()) {
+                throw new IllegalStateException(
+                    String.format("There is no directory %s present The extension cannot be installed.", libExtDir));
```
Comment (bartoszmajsak) [inline functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionRegisterer.java]: Instead of failing can we create it on the fly instead?

File: functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionRegisterer.java [hunk 4]
```diff
@@ -36,4 +42,37 @@ void addSmartTestingExtension(String version) {
         }
     }
 
+    void addSmartTestingShadedExtensionIntoLibExtFolder(String stVersion, String maven3Version) {
```
Comment (bartoszmajsak) [inline functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionRegisterer.java]: I was wondering if it would make sense to have 2 classes here - one for installing extension using the new way and other for old-school way? In addition maybe slicing this method body to smaller methods named in the way that it's clear what are the steps involved could be useful?

File: functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectBuilder.java [hunk 5]
```diff
@@ -113,9 +115,23 @@ private String printSystemProperties() {
...
+            if (mvnInstallation != null) {
+                embeddedMaven.useInstallation(new File(mvnInstallation));
+            }
+        }
+    }
+
+    private void setMaven3Version(PomEquippedEmbeddedMaven embeddedMaven) {
+        String maven3Version = buildConfigurator.getMaven3Version();
+        embeddedMaven.useMaven3Version(maven3Version);
+        if (!new File(MavenExtensionRegisterer.DOT_MVN_DIR, MavenExtensionRegisterer.EXTENSIONS_XML).exists()) {
```
Comment (bartoszmajsak) [inline functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectBuilder.java]: It would be easier for me to understand what is the condition if this could be extracted to the separated method (or variable) with the self-explaining name. Do you feel like it would improve it too from your perception?

File: functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/DebugMode325MavenSmartTestingFunctionalTest.java [hunk 6]
```diff
@@ -28,28 +32,32 @@
...
+        throws Exception {
         // given
         final Project project = testBed.getProject();
 
         project.configureSmartTesting()
                 .executionOrder(AFFECTED)
-                .inMode(ORDERING)
-            .enable();
+                .inMode(SELECTING)
+            .enable(false);
```
Comment (bartoszmajsak) [inline functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/DebugMode325MavenSmartTestingFunctionalTest.java]: This is a bit unclear for me - flag, as well as parameter name ('install'), doesn't really explain what is the intended behaviour here. Maybe we can think of `enable(Using.EXTENSION_FILE)` or `enable(Using.SHADED_JAR)` and having `enable()` defaulted like it is now? With `enum`/strategy approach we can easily encapsulate these two different setup approaches as I hinted in the comment above.

**Comment by bartoszmajsak** [comment]
Oh, didn't notice that you removed me as a reviewer! Sorry!

File: functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionRegisterer.java (hunk 4 above)
Comment (MatousJobanek) [reply functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionRegisterer.java]: Personally, I would keep it inside of one class - it makes sense for me as both cases is just registering the ST extension, which is pretty good explained by the class name: `MavenExtensionRegisterer`. Are you fine with it? If not, then which names do you propose for the classes in case it was separated.
But yeah, I can slice the method to smaller pieces 👍

Comment (MatousJobanek) [reply functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionRegisterer.java]: Ok, I just got to this: https://github.com/arquillian/smart-testing/pull/209/files#r143059742
The names would be:
* `MavenExtensionFileRegisterer`
* `MavenExtensionShadedJarRegisterer`

**Comment by MatousJobanek** [comment]
I didn't remove you (you haven't been a reviewer of this PR ever) :-D I didn't put you on the list of reviewers as you were/are out ;-)
And mainly, you have already commented so it wasn't necessary to add you there as you get the notification anyway :-)

**Comment by MatousJobanek** [comment]
As for your discussions related to the ftest of the shaded plugin: https://github.com/arquillian/smart-testing/pull/209#issuecomment-334592453
When I was writing the ftest I figured out that the jar [cannot be minimized](https://github.com/arquillian/smart-testing/pull/209/commits/fe1ca8c379a74338a23de1d6d95045aef765f7c2) otherwise the extension is not loaded correctly.

File: functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionShadedJarRegisterer.java [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+import java.nio.file.Path;
+import java.nio.file.Paths;
+import java.util.Arrays;
+import java.util.Optional;
+import org.jboss.shrinkwrap.resolver.api.maven.Maven;
+
+class MavenExtensionShadedJarRegisterer {
+
+    MavenExtensionShadedJarRegisterer() {
+    }
```
Comment (dipak-pawar) [inline functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionShadedJarRegisterer.java]: I can see there is no another constructor of `MavenExtensionShadedJarRegisterer`. So no need to declare this

File: functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionShadedJarRegisterer.java [hunk 8]
```diff
@@ -0,0 +1,65 @@
...
+            }
+        });
+        return libExtDir;
+    }
+
+    private Path getMvnHome(String mavenVersion) throws IOException {
+        String mvnHomeName = "apache-maven-" + mavenVersion;
+        Path resolverMaven = Paths.get("target","resolver-maven").toAbsolutePath();
+
+        Optional<Path> mvnHome = Files.walk(resolverMaven)
```
Comment (dipak-pawar) [inline functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionShadedJarRegisterer.java]:
```java
        return Files.walk(resolverMaven)
            .filter(path -> path.toFile().isDirectory() && (mvnHomeName).equals(path.toFile().getName()))
            .findFirst()
            .orElseThrow(() -> new IllegalStateException(String.format(
                                "There is no %s directory present inside of the %s directory. The extension cannot be installed.",
                                mvnHomeName, resolverMaven)));

File: functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/DebugMode325MavenSmartTestingFunctionalTest.java [hunk 9]
```diff
@@ -13,12 +16,14 @@
...
 import static org.arquillian.smart.testing.ftest.testbed.configuration.Mode.ORDERING;
+import static org.arquillian.smart.testing.ftest.testbed.configuration.Mode.SELECTING;
 import static org.arquillian.smart.testing.ftest.testbed.configuration.Strategy.AFFECTED;
+import static org.arquillian.smart.testing.scm.ScmRunnerProperties.SCM_LAST_CHANGES;
 import static org.arquillian.smart.testing.scm.ScmRunnerProperties.SCM_RANGE_HEAD;
 import static org.arquillian.smart.testing.scm.ScmRunnerProperties.SCM_RANGE_TAIL;
 import static org.assertj.core.api.Assertions.assertThat;
 
-public class DebugModeSmartTestingFunctionalTest {
+public class DebugMode325MavenSmartTestingFunctionalTest {
```
Comment (dipak-pawar) [inline functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/DebugMode325MavenSmartTestingFunctionalTest.java]: I can see class name changed from `DebugModeSmartTestingFunctionalTest` to  `DebugMode325MavenSmartTestingFunctionalTest`. But looks like this class also contains another test with name `should_show_debug_logs_when_maven_is_executed_in_debug_mode` where we are not using maven version `3.2.5`. We should not change this class name as I believe we are already defining maven version in test method name

Comment (MatousJobanek) [reply functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/DebugMode325MavenSmartTestingFunctionalTest.java]: The rename was meant to point out that this class is testing also different Maven version - easy to find.
The reason why I added it into existing test is that I didn't want to add another functional test that would make the test execution longer. 
As for the name - well, it is quite hard to describe all test method variants in the class name.

Comment (dipak-pawar) [reply functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/DebugMode325MavenSmartTestingFunctionalTest.java]: But maybe we can create separate class with name `DebugModeMaven325SmartTestingFunctionalTest` & move it there this existing tests

Comment (MatousJobanek) [reply functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/DebugMode325MavenSmartTestingFunctionalTest.java]: I was thinking about it as well, but I'd like to keep all debug related tests inside of one test class. How about rename it to `DebugModeAnd325MavenFunctionalTest`?

Comment (dipak-pawar) [reply functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/DebugMode325MavenSmartTestingFunctionalTest.java]: Can we make it `DebugModeAndMaven325FunctionalTest` ?
