### PR TITLE
fix(#245): Allows different versions of JUnit in same project

### LINKED ISSUE #245: JUnit5 and JUnit4 cannot be mixed
Currently a project can only work in JUnit 4 or JUnit 5 but cannot work in cases where one module of the project uses JUnit 4 and other in JUnit 5 in forked surefire configuration.

### PR DESCRIPTION
**Pull request by lordofthejars**
#### Short description of what this resolves:

Adds creation of different version files depending if junit5 is defined in surefire or failsafe, also taking into consideration defining different versions of JUnit through different modules.

#### Changes proposed in this pull request:

- Create one file storing JUnit5 version in each module directory and named _failsafe_ or _surefire_.

Fixes #245

### CODE REVIEW

File: core/src/main/java/org/arquillian/smart/testing/hub/storage/local/LocalStorage.java [hunk 1]
```diff
@@ -7,6 +7,8 @@
  */
 public class LocalStorage {
 
+    public static String JUNIT_5_PLATFORM_VERSION = "junit5PlatformVersion";
```
Comment (bartoszmajsak) [inline core/src/main/java/org/arquillian/smart/testing/hub/storage/local/LocalStorage.java]: Minor thing - I'm not sure this should belong here - it's not related to storage at all. Maybe `LoaderVersionExtractor` would be a better place?

File: surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/info/JUnit5ProviderInfo.java [hunk 2]
```diff
@@ -11,28 +12,31 @@
 
     private String junit5SurefirePlatformVersion;
 
-    public JUnit5ProviderInfo() {
-        super(LoaderVersionExtractor.getJUnit5Version());
-        junit5SurefirePlatformVersion = retrieveJunit5SurefirePlatformVersion();
+    public JUnit5ProviderInfo(File projectDir) {
+        super(null);
```
Comment (bartoszmajsak) [inline surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/info/JUnit5ProviderInfo.java]: Any particular reason why extend from `JUnitProviderInfo` instead of implementing `ProviderInfo`? This `null` looks weird.

File: surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/LoaderVersionExtractorSurefireJUnit5Test.java [hunk 3]
```diff
@@ -1,50 +0,0 @@
...
-import java.util.Collection;
-import org.jboss.shrinkwrap.resolver.api.maven.Maven;
-import org.junit.Test;
-import org.junit.runner.RunWith;
-import org.junit.runners.Parameterized;
-
-import static org.assertj.core.api.Assertions.assertThat;
-
-@RunWith(Parameterized.class)
-public class LoaderVersionExtractorSurefireJUnit5Test {
```
Comment (bartoszmajsak) [inline surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/LoaderVersionExtractorSurefireJUnit5Test.java]: Those two tests were removed in favor of `JUnit5ProviderInfoTest`?

File: core/src/main/java/org/arquillian/smart/testing/hub/storage/local/LocalStorage.java (hunk 1 above)
Comment (MatousJobanek) [reply core/src/main/java/org/arquillian/smart/testing/hub/storage/local/LocalStorage.java]: The reason why we put it here is that we need to have it available on both sides - maven extension and surefire
We had the same discussion - where we should put it and we decided for this place

Comment (bartoszmajsak) [reply core/src/main/java/org/arquillian/smart/testing/hub/storage/local/LocalStorage.java]: Don't we have `LoaderVersionExtractor` available for both side though?

File: surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/info/JUnit5ProviderInfo.java (hunk 2 above)
Comment (MatousJobanek) [reply surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/info/JUnit5ProviderInfo.java]: good point - this is kind of zombie

File: surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/LoaderVersionExtractorSurefireJUnit5Test.java (hunk 3 above)
Comment (MatousJobanek) [reply surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/LoaderVersionExtractorSurefireJUnit5Test.java]: nope, there have been removed methods that were getting the version so the tests are not needed https://github.com/arquillian/smart-testing/pull/246/files#diff-f265edf8b316db4ccfc2829915f4af85L46

**Comment by bartoszmajsak** [comment]
Thanks guys!
