### PR TITLE
Fixes build execution when using multiple forks

### LINKED ISSUE #124: Surefire fork failures with our provider
When the number of thread/surefire foks is set to more than one, and `reuseForks=true` then it fails with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project arquillian-config-impl-base: ExecutionException There was an error in the forked process
[ERROR] java.util.NoSuchElementException: 
[ERROR] 	at org.apache.maven.surefire.booter.CommandReader$ClassesIterator.next(CommandReader.java:275)
[ERROR] 	at org.apache.maven.surefire.booter.CommandReader$ClassesIterator.next(CommandReader.java:248)
[ERROR] 	at org.apache.maven.surefire.booter.LazyTestsToRun$BlockingIterator.next(LazyTestsToRun.java:73)
[ERROR] 	at org.apache.maven.surefire.booter.LazyTestsToRun$BlockingIterator.next(LazyTestsToRun.java:61)
[ERROR] 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
[ERROR] 	at org.arquillian.smart.testing.surefire.provider.SmartTestingSurefireProvider.invoke(SmartTestingSurefireProvider.java:66)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

Does not matter which strategy is chosen.

### PR DESCRIPTION
**Pull request by bartoszmajsak**
#### Short description of what this resolves:

This fix solves the remaining issue when using Smart Testing provider with forked surefires.

What I have noticed during the analysis of this problem is that provider is executed on both sides - the main thread (booter) and forked processes. It can happen that the forked process might have none tests passed (probably) but then we are marking execution of this process as completed with result `noTestsToRun` and we don't call actual provider (delegate). This somehow seems to break the protocol (shared output stream) between fork booter and surefire forks. Thus we have `NoSuchElementException` as we prematurely mark process as finishedin the `CommandReader`

#### Changes proposed in this pull request:

- Removes now not needed check if `orderedTests` contain any elements and mark execution as finished with no tests to run. It was introduced to mitigate the problem of surefire failing when `selecting` mode had no tests for the given module. This is solved by additional method `getTestsToRun()` added after this bit.
- Shuffled `public` and `private` methods in the provider for better structure

Fixes #124

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Follow up on the analysis. In case of forked processes, Surefire Booter sends list of classes assigned to a given fork and empty `""` at the end of the lazily evaluated tests to run in order to communicate to the forked process that its' life has ended.

What we were doing here
```java
if (orderedTests.containsExactly(0)) {
    orderedTests.markTestSetFinished();
    return RunResult.noTestsRun();
}
```

was that we were prematurely closing it without letting fork to properly handle `""` message. That's what I think was the root cause of `NoSuchElementException`.

File: functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectBuilder.java [hunk 1]
```diff
@@ -70,6 +70,7 @@ private BuiltProject executeGoals(String... goals) {
                     .setProperties(asProperties(buildConfigurator.getSystemProperties()))
                     .skipTests(buildConfigurator.isSkipTestsEnabled())
                     .setMavenOpts(buildConfigurator.getMavenOpts())
+                    .setAlsoMake(true)
```
Comment (MatousJobanek) [inline functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectBuilder.java]: This has been already committed to the master branch: 
https://github.com/arquillian/smart-testing/commit/cf6f1d0c153ce1bfc7c3c91218f2298e487bb7ce

Comment (bartoszmajsak) [reply functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectBuilder.java]: I know, I cherry-picked from here. Makes me wonder why it still shows up though...
