### PR TITLE
Fixes NPE for empty config file.

### LINKED ISSUE #248: Getting NPE if providing empty smart-testing.yml
*Steps To Reproduce*
* Create empty config file `smart-testing.yml` in project's root dir.
* Run test with `mvn test`

*Actual Result*
Getting NPE 

*Expected Result*
We should get appropriate msg if config file is empty

### PR DESCRIPTION
**Pull request by dipak-pawar**
Fixes #248

### CODE REVIEW

File: core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java [hunk 1]
```diff
@@ -155,9 +155,13 @@ public static Configuration load(File projectDir) {
             logger.info("Config file `" + SMART_TESTING_YAML + "` OR `" + SMART_TESTING_YML + "` is not found. "
                 + "Using system properties to load configuration for smart testing.");
         } else {
-            try (InputStream io = Files.newInputStream(getConfigurationFilePath(files))) {
+            final Path filePath = getConfigurationFilePath(files);
+            try (InputStream io = Files.newInputStream(filePath)) {
                 final Yaml yaml = new Yaml();
                 yamlConfiguration = yaml.load(io);
+                if (yamlConfiguration == null) {
```
Comment (lordofthejars) [inline core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java]: What's happening if file is empty but there are system properties set? Should we fail? Maybe the file is empty because someone else is the responsible of configuring.

File: core/src/test/java/org/arquillian/smart/testing/configuration/ConfigurationTest.java [hunk 2]
```diff
@@ -15,6 +20,12 @@
 
 public class ConfigurationTest {
 
+    @Rule
+    public TemporaryFolder temporaryFolder = new TemporaryFolder();
+
+    @Rule
```
Comment (lordofthejars) [inline core/src/test/java/org/arquillian/smart/testing/configuration/ConfigurationTest.java]: Use assertJ assertions instead of this rule http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#exception-assertion

File: core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java (hunk 1 above)
Comment (lordofthejars) [reply core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java]: I am just thinking loudly

Comment (MatousJobanek) [reply core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java]: I would expect that if the file is empty then we should not fail, just load the default values or those taken from system properties.
The only thing what we can do in this case is just logging the information/warn that the file is empty.

Comment (bartoszmajsak) [reply core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java]: I would log warning too to be honest. I guess that's what we do with empty `arquillian.xml` for example? Only fail when no sysprops are defined as well.

Comment (lordofthejars) [reply core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java]: Not sure about `arquillian.xml` but I guess that just warning is ok in this case. I agree with @MatousJobanek approach.

**Comment by MatousJobanek** [comment]
I introduced a few refactoring changes and a test case + rebased with the master branch & resolved the conflicts
